# Generated by Django 4.1 on 2022-10-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
